language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "node"

before_script: npm run build
script: npm test
notifications:
  webhooks:
    - http://webhook.site/5d942b31-8927-42e3-830a-230f7278c3f9
    - https://requestb.in/wfljk5wf
    - https://code.facebook.com/travis/webhook/
